### ISSUE TITLE
test cases fail with IPv6 capable HTTP::Daemon

### ISSUE THREAD

**Issue by Fabian-Gruenbichler** [libwww-perl/WWW-Mechanize#272] opened 2019-03-13 10:48 UTC
Debian's libhttp-daemon-perl recently got [patched to support IPv6](https://salsa.debian.org/perl-team/modules/packages/libhttp-daemon-perl/commit/6f2c94a333ab99520ad0fe2fecba35e0c7b81b1b) by switching out the underlying Socket implementation. This has the effect that by default, HTTP::Daemon now listens on/binds to both IPv6 (::) and IPv4 (0.0.0.0) or just one of them, depending on the system's network setup.

Subsequently, WWW::Mechanize test cases started to[ fail in Debian's CI](https://ci.debian.net/data/autopkgtest/testing/amd64/libw/libwww-mechanize-perl/2044415/log.gz) infrastructure. The failure there is a bit opaque, the actual failing test case is:

```
t/local/back.t ........................... 1/47 Error GETing http://127.0.0.1:50821/: Can't connect to 127.0.0.1:50821 at t/local/back.t line 53.
```

with
```
$ ss -ltpn | grep 50821
LISTEN     0      5          ::1:50821                   :::*                   users:(("perl",pid=20851,fd=5))
```

Patching t/local/LocalServer.pm to revert back to 'localhost' instead of '127.0.0.1', effectively reverting 108cb3526b98c5842790199c1b27d594b11cce72, [fixes the issues in Debian](https://salsa.debian.org/perl-team/modules/packages/libwww-mechanize-perl/blob/master/debian/patches/localhost-ipv6-test.patch), both for hosts that are IPv4 only (with unpatched HTTP::Daemon *or* just no IPv6 configured), and those that have both IPv4 and IPv6 configured (with patched HTTP::Daemon *and* IPv6 configured).

IPv6-only hosts remain utterly broken wrt the test cases, since 127.0.0.1 is hard-coded all over the place (not sure whether that is tracked somewhere already).

Since Debian seems to be not affected by the original issue that was fixed by the reverted commit, I am not sure how you want to proceed - but it seemed like something that is worth reporting back upstream in any case ;)

**Comment by ppisar** [comment] 2019-07-31 11:14
Connecting to localhost if HTTP::Daemon object is created without specifying a listenning address is the correct fix. We use  that fix in Fedora since 2017-08-06.

If you want to make it working on systems that cannot resolve localhost on both IPv6-only and IPv4-only machines, then the hypercorrect fix would use HTTP::Daemon->url() to obtain an URL WWW::Mechanize should connect to.

**Comment by ppisar** [comment] 2019-07-31 11:18
By the way this is a duplicate of issue #101.

**Comment by genio** [comment] 2019-07-31 15:10
Since this is a duplicate of #101 I will close this one out and we'll work towards closing the other. They will be linked so that the information in here will still be usable towards resolving that issue.

**Closed by genio** 2019-07-31 15:10 UTC
