### ISSUE TITLE
WM: uri() dies if no request has been performed

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#210] opened 2017-05-08 06:02 UTC
michael....@gmail.com reported on Mar 25, 2012 

<pre>
    use 5.014;
    use WWW::Mechanize;

    my $mech = WWW::Mechanize;
    say $mech-&gt;uri();

gives:

    Can&#39;t call method &quot;request&quot; on an undefined value at /opt/perl-5.14/lib/site_perl/5.14.2/WWW/Mechanize.pm

uri() should probably just return null if no request has been performed, like other methods (such as content()).

WWW::Mechanize version 1.72.

 – Michael
</pre>

### Details

Imported from [Google Code issue 233](http://code.google.com/p/www-mechanize/issues/detail?id=233) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=233)

* **Type**:      Defect
* **Date**:      Mar 25, 2012
* **Reporter**:  michael....@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New

**Comment by zackse** [comment] 2017-10-25 00:24
This is a dupe of #60 and was fixed in 8c04c9a35e60c7cdda4283ecfc5c9a820d79b5f6.

**Comment by oalders** [comment] 2018-10-15 14:47
Thanks @zackse!

**Closed by oalders** 2018-10-15 14:47 UTC
