### ISSUE TITLE
Failed dump_links test (due to runtime error) during cpanm install on Ubuntu 10.04.4, perl v5.20.0

### ISSUE THREAD

**Issue by mishagale** [libwww-perl/WWW-Mechanize#79] opened 2017-02-01 15:22 UTC
WWW-Mechanize-1.83

[Full build log](https://github.com/libwww-perl/WWW-Mechanize/files/745235/www-mech-build-log.txt)

Relevant error:

```
Use of uninitialized value $method in method lookup at t/dump.t line 132.
Can't locate object method "" via package "WWW::Mechanize" at t/dump.t line 132.
    # Child (dump_links test) exited without calling finalize()

#   Failed test 'dump_links test'
#   at /opt/perlbrew/perls/perl-5.20.0/lib/5.20.0/Test/Builder.pm line 276.
# Looks like you planned 6 tests but ran 3.
# Looks like you failed 1 test of 3 run.
# Looks like your test exited with 255 just after 3.
t/dump.t ................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/6 subtests 

```

**Comment by oalders** [comment] 2017-02-01 16:20
This looks to be a duplicate of #74, which has been fixed.  Let me know if that's not the case and I'll re-open this ticket.  We just need to get a new release out, which we can do this week.

**Closed by oalders** 2017-02-01 16:20 UTC

**Comment by mishagale** [comment] 2017-02-01 16:29
Confirmed, updating my Test::Builder allowed WWW::Mechanize tests to pass. Thanks!
